import api from "./api";

export interface AvailableUser {
  id: number;
  email: string;
  fullName: string;
}

export interface Employee {
  id: number;
  employeeCode?: string; // Optional since it's auto-generated by backend
  fullName: string;
  phone?: string;
  address?: string;
  birthDate?: string;
  position?: string;
  salary: number;
  identityCard?: string;
  userId?: number | null;
  user?: AvailableUser | null;
  createdAt: string;
  updatedAt: string;
}

export const employeeService = {
  getAll: async (keyword?: string) => {
    const kw = keyword?.trim();
    const response = await api.get<{ data: Employee[] }>("/employee", {
      params: kw ? { keyword: kw } : {},
    });
    return response.data.data;
  },

  getById: async (id: number) => {
    const response = await api.get<{ data: Employee }>(`/employee/${id}`);
    return response.data.data;
  },

  create: async (
    data: Omit<
      Employee,
      "id" | "createdAt" | "updatedAt" | "employeeCode" | "user"
    >,
  ) => {
    const response = await api.post<{ data: Employee }>("/employee", data);
    return response.data.data;
  },

  update: async (id: number, data: Partial<Omit<Employee, "user">>) => {
    const response = await api.patch<{ data: Employee }>(
      `/employee/${id}`,
      data,
    );
    return response.data.data;
  },

  delete: async (id: number) => {
    await api.delete(`/employee/${id}`);
  },

  deleteMany: async (ids: number[], reason?: string) => {
    await api.delete("/employee/bulk", {
      data: { ids, reason },
    });
  },

  getAvailableUsers: async (
    excludeEmployeeId?: number,
  ): Promise<AvailableUser[]> => {
    const params = excludeEmployeeId
      ? `?excludeEmployeeId=${excludeEmployeeId}`
      : "";
    const response = await api.get<{ data: AvailableUser[] }>(
      `/employee/available-users${params}`,
    );
    // Backend trả về trực tiếp mảng hoặc bọc trong { data }
    const raw = response.data as unknown;
    if (Array.isArray(raw)) return raw as AvailableUser[];
    if (raw && typeof raw === "object" && "data" in raw) {
      return (raw as { data: AvailableUser[] }).data;
    }
    return [];
  },
};
