export interface User {
  id: number;
  email: string;
  fullName: string;
  role: any; // eslint-disable-line @typescript-eslint/no-explicit-any
  status?: string;
  employee?: {
    employeeCode: string;
    fullName: string;
  };
  updatedAt?: string;
  updater?: {
    fullName: string;
  };
}

export interface ApiResponse<T> {
  code: number;
  status: boolean;
  message: string;
  data: T;
}

export interface LoginResponse {
  data: {
    accessToken: string;
    refreshToken: string;
    user: User;
  };
  message: string;
}

export interface Product {
  id: number;
  name: string;
  price: number;
  categoryId: number;
  description?: string;
}

export enum Permission {
  // --- USER PERMISSIONS ---
  USER_VIEW = "USER_VIEW",
  USER_CREATE = "USER_CREATE",
  USER_UPDATE = "USER_UPDATE",
  USER_DELETE = "USER_DELETE",
  USER_SEARCH = "USER_SEARCH",
  USER_APPROVE = "USER_APPROVE",
  USER_MANAGE = "USER_MANAGE",

  // --- PRODUCT PERMISSIONS ---
  PRODUCT_VIEW = "PRODUCT_VIEW",
  PRODUCT_CREATE = "PRODUCT_CREATE",
  PRODUCT_UPDATE = "PRODUCT_UPDATE",
  PRODUCT_DELETE = "PRODUCT_DELETE",
  PRODUCT_SEARCH = "PRODUCT_SEARCH",
  PRODUCT_APPROVE = "PRODUCT_APPROVE",

  // --- ORDER PERMISSIONS ---
  ORDER_VIEW = "ORDER_VIEW",
  ORDER_CREATE = "ORDER_CREATE",
  ORDER_UPDATE = "ORDER_UPDATE",
  ORDER_DELETE = "ORDER_DELETE",
  ORDER_CANCEL = "ORDER_CANCEL",
  ORDER_SEARCH = "ORDER_SEARCH",
  ORDER_APPROVE = "ORDER_APPROVE",

  // --- INVOICE PERMISSIONS ---
  INVOICE_VIEW = "INVOICE_VIEW",
  INVOICE_CREATE = "INVOICE_CREATE",
  INVOICE_CANCEL = "INVOICE_CANCEL",
  INVOICE_PAY = "INVOICE_PAY",
  INVOICE_SEARCH = "INVOICE_SEARCH",
  INVOICE_APPROVE = "INVOICE_APPROVE",

  // --- OTHER PERMISSIONS ---
  SETTING_MANAGE = "SETTING_MANAGE",
  LOG_VIEW = "LOG_VIEW",
  LOG_DELETE = "LOG_DELETE",

  // --- EMPLOYEE PERMISSIONS ---
  EMPLOYEE_VIEW = "EMPLOYEE_VIEW",
  EMPLOYEE_CREATE = "EMPLOYEE_CREATE",
  EMPLOYEE_UPDATE = "EMPLOYEE_UPDATE",
  EMPLOYEE_DELETE = "EMPLOYEE_DELETE",
  EMPLOYEE_SEARCH = "EMPLOYEE_SEARCH",
  EMPLOYEE_APPROVE = "EMPLOYEE_APPROVE",

  // --- AREA PERMISSIONS ---
  AREA_VIEW = "AREA_VIEW",
  AREA_CREATE = "AREA_CREATE",
  AREA_UPDATE = "AREA_UPDATE",
  AREA_DELETE = "AREA_DELETE",
  AREA_SEARCH = "AREA_SEARCH",
  AREA_APPROVE = "AREA_APPROVE",

  // --- TABLE PERMISSIONS ---
  TABLE_VIEW = "TABLE_VIEW",
  TABLE_CREATE = "TABLE_CREATE",
  TABLE_UPDATE = "TABLE_UPDATE",
  TABLE_DELETE = "TABLE_DELETE",
  TABLE_SEARCH = "TABLE_SEARCH",
  TABLE_APPROVE = "TABLE_APPROVE",

  // --- APPROVAL PERMISSIONS ---
  APPROVAL_VIEW = "APPROVAL_VIEW",
  APPROVAL_CREATE = "APPROVAL_CREATE",
  APPROVAL_UPDATE = "APPROVAL_UPDATE",
  APPROVAL_DELETE = "APPROVAL_DELETE",
  APPROVAL_SEARCH = "APPROVAL_SEARCH",
  APPROVAL_APPROVE = "APPROVAL_APPROVE",
  APPROVAL_MANAGE = "APPROVAL_MANAGE",

  // --- STATISTICS PERMISSIONS ---
  STATISTICS_VIEW = "STATISTICS_VIEW",
  STATISTICS_EXPORT = "STATISTICS_EXPORT",
  STATISTICS_SEARCH = "STATISTICS_SEARCH",
  STATISTICS_APPROVE = "STATISTICS_APPROVE",

  // --- AI ASSISTANT PERMISSIONS ---
  AI_ASSISTANT_CHAT = "AI_ASSISTANT_CHAT",
  AI_ASSISTANT_MANAGE = "AI_ASSISTANT_MANAGE",
  AI_ASSISTANT_SEARCH = "AI_ASSISTANT_SEARCH",
  AI_ASSISTANT_APPROVE = "AI_ASSISTANT_APPROVE",

  // --- CATEGORY PERMISSIONS ---
  CATEGORY_VIEW = "CATEGORY_VIEW",
  CATEGORY_CREATE = "CATEGORY_CREATE",
  CATEGORY_UPDATE = "CATEGORY_UPDATE",
  CATEGORY_DELETE = "CATEGORY_DELETE",
  CATEGORY_SEARCH = "CATEGORY_SEARCH",
  CATEGORY_APPROVE = "CATEGORY_APPROVE",

  // --- ROLE PERMISSIONS ---
  ROLE_VIEW = "ROLE_VIEW",
  ROLE_CREATE = "ROLE_CREATE",
  ROLE_UPDATE = "ROLE_UPDATE",
  ROLE_DELETE = "ROLE_DELETE",
  ROLE_SEARCH = "ROLE_SEARCH",
  ROLE_APPROVE = "ROLE_APPROVE",

  // --- LOGGING PERMISSIONS ---
  LOGGING_VIEW = "LOGGING_VIEW",
  LOGGING_DELETE = "LOGGING_DELETE",

  // --- NOTIFICATION PERMISSIONS ---
  NOTIFICATION_VIEW = "NOTIFICATION_VIEW",
  NOTIFICATION_CREATE = "NOTIFICATION_CREATE",
  NOTIFICATION_UPDATE = "NOTIFICATION_UPDATE",
  NOTIFICATION_DELETE = "NOTIFICATION_DELETE",
  NOTIFICATION_SEARCH = "NOTIFICATION_SEARCH",
  NOTIFICATION_APPROVE = "NOTIFICATION_APPROVE",

  // --- DASHBOARD PERMISSIONS ---
  DASHBOARD_VIEW = "DASHBOARD_VIEW",
}
