export interface User {
  id: number;
  email: string;
  fullName: string;
  role: any; // eslint-disable-line @typescript-eslint/no-explicit-any
  status?: string;
  employee?: {
    employeeCode: string;
    fullName: string;
  };
  updatedAt?: string;
  updater?: {
    fullName: string;
  };
}

export interface ApiResponse<T> {
  code: number;
  status: boolean;
  message: string;
  data: T;
}

export interface LoginResponse {
  data: {
    accessToken: string;
    refreshToken: string;
    user: User;
  };
  message: string;
}

export interface Product {
  id: number;
  name: string;
  price: number;
  categoryId: number;
  description?: string;
}

export enum Permission {
  // --- DASHBOARD ---
  DASHBOARD_MENU = "DASHBOARD_MENU",
  DASHBOARD_VIEW = "DASHBOARD_VIEW",

  // --- AREA ---
  AREA_MENU = "AREA_MENU",
  AREA_VIEW = "AREA_VIEW",
  AREA_CREATE = "AREA_CREATE",
  AREA_UPDATE = "AREA_UPDATE",
  AREA_DELETE = "AREA_DELETE",
  AREA_APPROVE = "AREA_APPROVE",

  // --- TABLE ---
  TABLE_MENU = "TABLE_MENU",
  TABLE_VIEW = "TABLE_VIEW",
  TABLE_CREATE = "TABLE_CREATE",
  TABLE_UPDATE = "TABLE_UPDATE",
  TABLE_DELETE = "TABLE_DELETE",
  TABLE_APPROVE = "TABLE_APPROVE",

  // --- CATEGORY ---
  CATEGORY_MENU = "CATEGORY_MENU",
  CATEGORY_VIEW = "CATEGORY_VIEW",
  CATEGORY_CREATE = "CATEGORY_CREATE",
  CATEGORY_UPDATE = "CATEGORY_UPDATE",
  CATEGORY_DELETE = "CATEGORY_DELETE",
  CATEGORY_APPROVE = "CATEGORY_APPROVE",

  // --- PRODUCT ---
  PRODUCT_MENU = "PRODUCT_MENU",
  PRODUCT_VIEW = "PRODUCT_VIEW",
  PRODUCT_CREATE = "PRODUCT_CREATE",
  PRODUCT_UPDATE = "PRODUCT_UPDATE",
  PRODUCT_DELETE = "PRODUCT_DELETE",
  PRODUCT_APPROVE = "PRODUCT_APPROVE",

  // --- EMPLOYEE ---
  EMPLOYEE_MENU = "EMPLOYEE_MENU",
  EMPLOYEE_VIEW = "EMPLOYEE_VIEW",
  EMPLOYEE_CREATE = "EMPLOYEE_CREATE",
  EMPLOYEE_UPDATE = "EMPLOYEE_UPDATE",
  EMPLOYEE_DELETE = "EMPLOYEE_DELETE",
  EMPLOYEE_APPROVE = "EMPLOYEE_APPROVE",

  // --- USER ---
  USER_MENU = "USER_MENU",
  USER_VIEW = "USER_VIEW",
  USER_CREATE = "USER_CREATE",
  USER_UPDATE = "USER_UPDATE",
  USER_DELETE = "USER_DELETE",
  USER_APPROVE = "USER_APPROVE",
  USER_MANAGE = "USER_MANAGE",

  // --- ROLE ---
  ROLE_MENU = "ROLE_MENU",
  ROLE_VIEW = "ROLE_VIEW",
  ROLE_CREATE = "ROLE_CREATE",
  ROLE_UPDATE = "ROLE_UPDATE",
  ROLE_DELETE = "ROLE_DELETE",
  ROLE_APPROVE = "ROLE_APPROVE",

  // --- APPROVAL ---
  APPROVAL_MENU = "APPROVAL_MENU",
  APPROVAL_VIEW = "APPROVAL_VIEW",
  APPROVAL_APPROVE = "APPROVAL_APPROVE",
  APPROVAL_REJECT = "APPROVAL_REJECT",

  // --- ORDER ---
  ORDER_MENU = "ORDER_MENU",
  ORDER_VIEW = "ORDER_VIEW",
  ORDER_CREATE = "ORDER_CREATE",
  ORDER_UPDATE = "ORDER_UPDATE",
  ORDER_CANCEL = "ORDER_CANCEL",

  // --- INVOICE ---
  INVOICE_MENU = "INVOICE_MENU",
  INVOICE_VIEW = "INVOICE_VIEW",
  INVOICE_PAY = "INVOICE_PAY",
  INVOICE_CANCEL = "INVOICE_CANCEL",
  INVOICE_APPROVE = "INVOICE_APPROVE",

  // --- STATISTICS ---
  STATISTICS_MENU = "STATISTICS_MENU",
  STATISTICS_VIEW = "STATISTICS_VIEW",
  STATISTICS_EXPORT = "STATISTICS_EXPORT",

  // --- AI ASSISTANT ---
  AI_ASSISTANT_MENU = "AI_ASSISTANT_MENU",
  AI_ASSISTANT_CHAT = "AI_ASSISTANT_CHAT",

  // --- SETTING ---
  SETTING_MENU = "SETTING_MENU",
  SETTING_MANAGE = "SETTING_MANAGE",

  // --- LOGGING ---
  LOGGING_MENU = "LOGGING_MENU",
  LOGGING_VIEW = "LOGGING_VIEW",
}
